// <auto-generated />
using System;
using CohesionTest.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CohesionTest.Db.Migrations
{
    [DbContext(typeof(CTContext))]
    partial class CTContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("CohesionTest.Db.ServiceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BuildingCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("buildingCode");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdDate");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("currentStatus");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("ServiceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
